#############################################################################
# Makefile for building: visor_cliente.app/Contents/MacOS/visor_cliente
# Generated by qmake (3.0) (Qt 5.2.0)
# Project:  visorClient.pro
# Template: app
# Command: /Users/Patri/Applications/5.2.0/clang_64/bin/qmake -spec macx-clang CONFIG+=x86_64 -o Makefile visorClient.pro
#############################################################################

MAKEFILE      = Makefile

####### Compiler, tools and options

CC            = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang
CXX           = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang++
DEFINES       = -DAPP_DATADIR=\"/usr/local/share\" -DAPP_VARDIR=\"/var/lib/visor_cliente\" -DAPP_CONFFILE=\"/etc/visor_cliente.ini\" -DQT_NO_DEBUG -DQT_MULTIMEDIAWIDGETS_LIB -DQT_MULTIMEDIA_LIB -DQT_WIDGETS_LIB -DQT_NETWORK_LIB -DQT_GUI_LIB -DQT_CORE_LIB
CFLAGS        = -pipe -O2 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.9.sdk -mmacosx-version-min=10.6 -Wall -W -fPIE $(DEFINES)
CXXFLAGS      = -pipe -O2 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.9.sdk -mmacosx-version-min=10.6 -Wall -W -fPIE $(DEFINES)
INCPATH       = -I../../../Applications/5.2.0/clang_64/mkspecs/macx-clang -I. -I/usr/local/include -I../../../Applications/5.2.0/clang_64/lib/QtMultimediaWidgets.framework/Versions/5/Headers -I../../../Applications/5.2.0/clang_64/lib/QtMultimedia.framework/Versions/5/Headers -I../../../Applications/5.2.0/clang_64/lib/QtWidgets.framework/Versions/5/Headers -I../../../Applications/5.2.0/clang_64/lib/QtNetwork.framework/Versions/5/Headers -I../../../Applications/5.2.0/clang_64/lib/QtGui.framework/Versions/5/Headers -I../../../Applications/5.2.0/clang_64/lib/QtCore.framework/Versions/5/Headers -Imoc -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.9.sdk/System/Library/Frameworks/OpenGL.framework/Versions/A/Headers -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.9.sdk/System/Library/Frameworks/AGL.framework/Headers -F/Users/Patri/Applications/5.2.0/clang_64/lib
LINK          = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang++
LFLAGS        = -headerpad_max_install_names -Wl,-syslibroot,/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.9.sdk -mmacosx-version-min=10.6
LIBS          = $(SUBLIBS) -F/Users/Patri/Applications/5.2.0/clang_64/lib -L/usr/local/lib -lopencv_core -lopencv_imgproc -lopencv_video -framework QtMultimediaWidgets -framework QtMultimedia -framework QtGui -framework QtCore -framework QtNetwork -framework QtWidgets -framework OpenGL -framework AGL 
AR            = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ar cq
RANLIB        = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib -s
QMAKE         = /Users/Patri/Applications/5.2.0/clang_64/bin/qmake
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
STRIP         = 
INSTALL_FILE  = $(COPY_FILE)
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = $(COPY_FILE)
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p

####### Output directory

OBJECTS_DIR   = object/

####### Files

SOURCES       = main.cpp \
		viewerwindow.cpp \
		capturebuffer.cpp \
		cvmatandqimage.cpp \
		worker.cpp moc/moc_viewerwindow.cpp \
		moc/moc_capturebuffer.cpp \
		moc/moc_worker.cpp
OBJECTS       = object/main.o \
		object/viewerwindow.o \
		object/capturebuffer.o \
		object/cvmatandqimage.o \
		object/worker.o \
		object/moc_viewerwindow.o \
		object/moc_capturebuffer.o \
		object/moc_worker.o
DIST          = ../../../Applications/5.2.0/clang_64/mkspecs/features/spec_pre.prf \
		../../../Applications/5.2.0/clang_64/mkspecs/qdevice.pri \
		../../../Applications/5.2.0/clang_64/mkspecs/features/device_config.prf \
		../../../Applications/5.2.0/clang_64/mkspecs/common/shell-unix.conf \
		../../../Applications/5.2.0/clang_64/mkspecs/common/unix.conf \
		../../../Applications/5.2.0/clang_64/mkspecs/common/mac.conf \
		../../../Applications/5.2.0/clang_64/mkspecs/common/macx.conf \
		../../../Applications/5.2.0/clang_64/mkspecs/common/gcc-base.conf \
		../../../Applications/5.2.0/clang_64/mkspecs/common/gcc-base-mac.conf \
		../../../Applications/5.2.0/clang_64/mkspecs/common/clang.conf \
		../../../Applications/5.2.0/clang_64/mkspecs/common/clang-mac.conf \
		../../../Applications/5.2.0/clang_64/mkspecs/qconfig.pri \
		../../../Applications/5.2.0/clang_64/mkspecs/modules/qt_lib_bluetooth.pri \
		../../../Applications/5.2.0/clang_64/mkspecs/modules/qt_lib_bluetooth_private.pri \
		../../../Applications/5.2.0/clang_64/mkspecs/modules/qt_lib_bootstrap_private.pri \
		../../../Applications/5.2.0/clang_64/mkspecs/modules/qt_lib_clucene_private.pri \
		../../../Applications/5.2.0/clang_64/mkspecs/modules/qt_lib_concurrent.pri \
		../../../Applications/5.2.0/clang_64/mkspecs/modules/qt_lib_concurrent_private.pri \
		../../../Applications/5.2.0/clang_64/mkspecs/modules/qt_lib_core.pri \
		../../../Applications/5.2.0/clang_64/mkspecs/modules/qt_lib_core_private.pri \
		../../../Applications/5.2.0/clang_64/mkspecs/modules/qt_lib_declarative.pri \
		../../../Applications/5.2.0/clang_64/mkspecs/modules/qt_lib_declarative_private.pri \
		../../../Applications/5.2.0/clang_64/mkspecs/modules/qt_lib_designer.pri \
		../../../Applications/5.2.0/clang_64/mkspecs/modules/qt_lib_designer_private.pri \
		../../../Applications/5.2.0/clang_64/mkspecs/modules/qt_lib_designercomponents_private.pri \
		../../../Applications/5.2.0/clang_64/mkspecs/modules/qt_lib_gui.pri \
		../../../Applications/5.2.0/clang_64/mkspecs/modules/qt_lib_gui_private.pri \
		../../../Applications/5.2.0/clang_64/mkspecs/modules/qt_lib_help.pri \
		../../../Applications/5.2.0/clang_64/mkspecs/modules/qt_lib_help_private.pri \
		../../../Applications/5.2.0/clang_64/mkspecs/modules/qt_lib_macextras.pri \
		../../../Applications/5.2.0/clang_64/mkspecs/modules/qt_lib_macextras_private.pri \
		../../../Applications/5.2.0/clang_64/mkspecs/modules/qt_lib_multimedia.pri \
		../../../Applications/5.2.0/clang_64/mkspecs/modules/qt_lib_multimedia_private.pri \
		../../../Applications/5.2.0/clang_64/mkspecs/modules/qt_lib_multimediawidgets.pri \
		../../../Applications/5.2.0/clang_64/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		../../../Applications/5.2.0/clang_64/mkspecs/modules/qt_lib_network.pri \
		../../../Applications/5.2.0/clang_64/mkspecs/modules/qt_lib_network_private.pri \
		../../../Applications/5.2.0/clang_64/mkspecs/modules/qt_lib_nfc.pri \
		../../../Applications/5.2.0/clang_64/mkspecs/modules/qt_lib_nfc_private.pri \
		../../../Applications/5.2.0/clang_64/mkspecs/modules/qt_lib_opengl.pri \
		../../../Applications/5.2.0/clang_64/mkspecs/modules/qt_lib_opengl_private.pri \
		../../../Applications/5.2.0/clang_64/mkspecs/modules/qt_lib_openglextensions.pri \
		../../../Applications/5.2.0/clang_64/mkspecs/modules/qt_lib_openglextensions_private.pri \
		../../../Applications/5.2.0/clang_64/mkspecs/modules/qt_lib_platformsupport_private.pri \
		../../../Applications/5.2.0/clang_64/mkspecs/modules/qt_lib_positioning.pri \
		../../../Applications/5.2.0/clang_64/mkspecs/modules/qt_lib_positioning_private.pri \
		../../../Applications/5.2.0/clang_64/mkspecs/modules/qt_lib_printsupport.pri \
		../../../Applications/5.2.0/clang_64/mkspecs/modules/qt_lib_printsupport_private.pri \
		../../../Applications/5.2.0/clang_64/mkspecs/modules/qt_lib_qml.pri \
		../../../Applications/5.2.0/clang_64/mkspecs/modules/qt_lib_qml_private.pri \
		../../../Applications/5.2.0/clang_64/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		../../../Applications/5.2.0/clang_64/mkspecs/modules/qt_lib_qmltest.pri \
		../../../Applications/5.2.0/clang_64/mkspecs/modules/qt_lib_qmltest_private.pri \
		../../../Applications/5.2.0/clang_64/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		../../../Applications/5.2.0/clang_64/mkspecs/modules/qt_lib_quick.pri \
		../../../Applications/5.2.0/clang_64/mkspecs/modules/qt_lib_quick_private.pri \
		../../../Applications/5.2.0/clang_64/mkspecs/modules/qt_lib_quickparticles_private.pri \
		../../../Applications/5.2.0/clang_64/mkspecs/modules/qt_lib_script.pri \
		../../../Applications/5.2.0/clang_64/mkspecs/modules/qt_lib_script_private.pri \
		../../../Applications/5.2.0/clang_64/mkspecs/modules/qt_lib_scripttools.pri \
		../../../Applications/5.2.0/clang_64/mkspecs/modules/qt_lib_scripttools_private.pri \
		../../../Applications/5.2.0/clang_64/mkspecs/modules/qt_lib_sensors.pri \
		../../../Applications/5.2.0/clang_64/mkspecs/modules/qt_lib_sensors_private.pri \
		../../../Applications/5.2.0/clang_64/mkspecs/modules/qt_lib_serialport.pri \
		../../../Applications/5.2.0/clang_64/mkspecs/modules/qt_lib_serialport_private.pri \
		../../../Applications/5.2.0/clang_64/mkspecs/modules/qt_lib_sql.pri \
		../../../Applications/5.2.0/clang_64/mkspecs/modules/qt_lib_sql_private.pri \
		../../../Applications/5.2.0/clang_64/mkspecs/modules/qt_lib_svg.pri \
		../../../Applications/5.2.0/clang_64/mkspecs/modules/qt_lib_svg_private.pri \
		../../../Applications/5.2.0/clang_64/mkspecs/modules/qt_lib_testlib.pri \
		../../../Applications/5.2.0/clang_64/mkspecs/modules/qt_lib_testlib_private.pri \
		../../../Applications/5.2.0/clang_64/mkspecs/modules/qt_lib_uitools.pri \
		../../../Applications/5.2.0/clang_64/mkspecs/modules/qt_lib_uitools_private.pri \
		../../../Applications/5.2.0/clang_64/mkspecs/modules/qt_lib_webkit.pri \
		../../../Applications/5.2.0/clang_64/mkspecs/modules/qt_lib_webkit_private.pri \
		../../../Applications/5.2.0/clang_64/mkspecs/modules/qt_lib_webkitwidgets.pri \
		../../../Applications/5.2.0/clang_64/mkspecs/modules/qt_lib_webkitwidgets_private.pri \
		../../../Applications/5.2.0/clang_64/mkspecs/modules/qt_lib_widgets.pri \
		../../../Applications/5.2.0/clang_64/mkspecs/modules/qt_lib_widgets_private.pri \
		../../../Applications/5.2.0/clang_64/mkspecs/modules/qt_lib_xml.pri \
		../../../Applications/5.2.0/clang_64/mkspecs/modules/qt_lib_xml_private.pri \
		../../../Applications/5.2.0/clang_64/mkspecs/modules/qt_lib_xmlpatterns.pri \
		../../../Applications/5.2.0/clang_64/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		../../../Applications/5.2.0/clang_64/mkspecs/features/qt_functions.prf \
		../../../Applications/5.2.0/clang_64/mkspecs/features/qt_config.prf \
		../../../Applications/5.2.0/clang_64/mkspecs/macx-clang/qmake.conf \
		../../../Applications/5.2.0/clang_64/mkspecs/features/spec_post.prf \
		../../../.qmake.stash \
		../../../Applications/5.2.0/clang_64/mkspecs/features/exclusive_builds.prf \
		../../../Applications/5.2.0/clang_64/mkspecs/features/default_pre.prf \
		../../../Applications/5.2.0/clang_64/mkspecs/features/mac/default_pre.prf \
		../../../Applications/5.2.0/clang_64/mkspecs/features/resolve_config.prf \
		../../../Applications/5.2.0/clang_64/mkspecs/features/default_post.prf \
		../../../Applications/5.2.0/clang_64/mkspecs/features/mac/sdk.prf \
		../../../Applications/5.2.0/clang_64/mkspecs/features/mac/default_post.prf \
		../../../Applications/5.2.0/clang_64/mkspecs/features/mac/objective_c.prf \
		../../../Applications/5.2.0/clang_64/mkspecs/features/warn_on.prf \
		../../../Applications/5.2.0/clang_64/mkspecs/features/qt.prf \
		../../../Applications/5.2.0/clang_64/mkspecs/features/resources.prf \
		../../../Applications/5.2.0/clang_64/mkspecs/features/moc.prf \
		../../../Applications/5.2.0/clang_64/mkspecs/features/unix/opengl.prf \
		../../../Applications/5.2.0/clang_64/mkspecs/features/uic.prf \
		../../../Applications/5.2.0/clang_64/mkspecs/features/unix/thread.prf \
		../../../Applications/5.2.0/clang_64/mkspecs/features/mac/rez.prf \
		../../../Applications/5.2.0/clang_64/mkspecs/features/testcase_targets.prf \
		../../../Applications/5.2.0/clang_64/mkspecs/features/exceptions.prf \
		../../../Applications/5.2.0/clang_64/mkspecs/features/yacc.prf \
		../../../Applications/5.2.0/clang_64/mkspecs/features/lex.prf \
		visorClient.pro \
		visorClient.pro
QMAKE_TARGET  = visor_cliente
DESTDIR       = #avoid trailing-slash linebreak
TARGET        = visor_cliente.app/Contents/MacOS/visor_cliente

####### Custom Compiler Variables
QMAKE_COMP_QMAKE_OBJECTIVE_CFLAGS = -pipe \
		-O2 \
		-isysroot \
		/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.9.sdk \
		-mmacosx-version-min=10.6 \
		-Wall \
		-W



first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile visor_cliente.app/Contents/PkgInfo visor_cliente.app/Contents/Resources/empty.lproj visor_cliente.app/Contents/Info.plist $(TARGET)

$(TARGET):  $(OBJECTS)  
	@test -d visor_cliente.app/Contents/MacOS/ || mkdir -p visor_cliente.app/Contents/MacOS/
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: visorClient.pro ../../../Applications/5.2.0/clang_64/mkspecs/macx-clang/qmake.conf ../../../Applications/5.2.0/clang_64/mkspecs/features/spec_pre.prf \
		../../../Applications/5.2.0/clang_64/mkspecs/qdevice.pri \
		../../../Applications/5.2.0/clang_64/mkspecs/features/device_config.prf \
		../../../Applications/5.2.0/clang_64/mkspecs/common/shell-unix.conf \
		../../../Applications/5.2.0/clang_64/mkspecs/common/unix.conf \
		../../../Applications/5.2.0/clang_64/mkspecs/common/mac.conf \
		../../../Applications/5.2.0/clang_64/mkspecs/common/macx.conf \
		../../../Applications/5.2.0/clang_64/mkspecs/common/gcc-base.conf \
		../../../Applications/5.2.0/clang_64/mkspecs/common/gcc-base-mac.conf \
		../../../Applications/5.2.0/clang_64/mkspecs/common/clang.conf \
		../../../Applications/5.2.0/clang_64/mkspecs/common/clang-mac.conf \
		../../../Applications/5.2.0/clang_64/mkspecs/qconfig.pri \
		../../../Applications/5.2.0/clang_64/mkspecs/modules/qt_lib_bluetooth.pri \
		../../../Applications/5.2.0/clang_64/mkspecs/modules/qt_lib_bluetooth_private.pri \
		../../../Applications/5.2.0/clang_64/mkspecs/modules/qt_lib_bootstrap_private.pri \
		../../../Applications/5.2.0/clang_64/mkspecs/modules/qt_lib_clucene_private.pri \
		../../../Applications/5.2.0/clang_64/mkspecs/modules/qt_lib_concurrent.pri \
		../../../Applications/5.2.0/clang_64/mkspecs/modules/qt_lib_concurrent_private.pri \
		../../../Applications/5.2.0/clang_64/mkspecs/modules/qt_lib_core.pri \
		../../../Applications/5.2.0/clang_64/mkspecs/modules/qt_lib_core_private.pri \
		../../../Applications/5.2.0/clang_64/mkspecs/modules/qt_lib_declarative.pri \
		../../../Applications/5.2.0/clang_64/mkspecs/modules/qt_lib_declarative_private.pri \
		../../../Applications/5.2.0/clang_64/mkspecs/modules/qt_lib_designer.pri \
		../../../Applications/5.2.0/clang_64/mkspecs/modules/qt_lib_designer_private.pri \
		../../../Applications/5.2.0/clang_64/mkspecs/modules/qt_lib_designercomponents_private.pri \
		../../../Applications/5.2.0/clang_64/mkspecs/modules/qt_lib_gui.pri \
		../../../Applications/5.2.0/clang_64/mkspecs/modules/qt_lib_gui_private.pri \
		../../../Applications/5.2.0/clang_64/mkspecs/modules/qt_lib_help.pri \
		../../../Applications/5.2.0/clang_64/mkspecs/modules/qt_lib_help_private.pri \
		../../../Applications/5.2.0/clang_64/mkspecs/modules/qt_lib_macextras.pri \
		../../../Applications/5.2.0/clang_64/mkspecs/modules/qt_lib_macextras_private.pri \
		../../../Applications/5.2.0/clang_64/mkspecs/modules/qt_lib_multimedia.pri \
		../../../Applications/5.2.0/clang_64/mkspecs/modules/qt_lib_multimedia_private.pri \
		../../../Applications/5.2.0/clang_64/mkspecs/modules/qt_lib_multimediawidgets.pri \
		../../../Applications/5.2.0/clang_64/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		../../../Applications/5.2.0/clang_64/mkspecs/modules/qt_lib_network.pri \
		../../../Applications/5.2.0/clang_64/mkspecs/modules/qt_lib_network_private.pri \
		../../../Applications/5.2.0/clang_64/mkspecs/modules/qt_lib_nfc.pri \
		../../../Applications/5.2.0/clang_64/mkspecs/modules/qt_lib_nfc_private.pri \
		../../../Applications/5.2.0/clang_64/mkspecs/modules/qt_lib_opengl.pri \
		../../../Applications/5.2.0/clang_64/mkspecs/modules/qt_lib_opengl_private.pri \
		../../../Applications/5.2.0/clang_64/mkspecs/modules/qt_lib_openglextensions.pri \
		../../../Applications/5.2.0/clang_64/mkspecs/modules/qt_lib_openglextensions_private.pri \
		../../../Applications/5.2.0/clang_64/mkspecs/modules/qt_lib_platformsupport_private.pri \
		../../../Applications/5.2.0/clang_64/mkspecs/modules/qt_lib_positioning.pri \
		../../../Applications/5.2.0/clang_64/mkspecs/modules/qt_lib_positioning_private.pri \
		../../../Applications/5.2.0/clang_64/mkspecs/modules/qt_lib_printsupport.pri \
		../../../Applications/5.2.0/clang_64/mkspecs/modules/qt_lib_printsupport_private.pri \
		../../../Applications/5.2.0/clang_64/mkspecs/modules/qt_lib_qml.pri \
		../../../Applications/5.2.0/clang_64/mkspecs/modules/qt_lib_qml_private.pri \
		../../../Applications/5.2.0/clang_64/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		../../../Applications/5.2.0/clang_64/mkspecs/modules/qt_lib_qmltest.pri \
		../../../Applications/5.2.0/clang_64/mkspecs/modules/qt_lib_qmltest_private.pri \
		../../../Applications/5.2.0/clang_64/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		../../../Applications/5.2.0/clang_64/mkspecs/modules/qt_lib_quick.pri \
		../../../Applications/5.2.0/clang_64/mkspecs/modules/qt_lib_quick_private.pri \
		../../../Applications/5.2.0/clang_64/mkspecs/modules/qt_lib_quickparticles_private.pri \
		../../../Applications/5.2.0/clang_64/mkspecs/modules/qt_lib_script.pri \
		../../../Applications/5.2.0/clang_64/mkspecs/modules/qt_lib_script_private.pri \
		../../../Applications/5.2.0/clang_64/mkspecs/modules/qt_lib_scripttools.pri \
		../../../Applications/5.2.0/clang_64/mkspecs/modules/qt_lib_scripttools_private.pri \
		../../../Applications/5.2.0/clang_64/mkspecs/modules/qt_lib_sensors.pri \
		../../../Applications/5.2.0/clang_64/mkspecs/modules/qt_lib_sensors_private.pri \
		../../../Applications/5.2.0/clang_64/mkspecs/modules/qt_lib_serialport.pri \
		../../../Applications/5.2.0/clang_64/mkspecs/modules/qt_lib_serialport_private.pri \
		../../../Applications/5.2.0/clang_64/mkspecs/modules/qt_lib_sql.pri \
		../../../Applications/5.2.0/clang_64/mkspecs/modules/qt_lib_sql_private.pri \
		../../../Applications/5.2.0/clang_64/mkspecs/modules/qt_lib_svg.pri \
		../../../Applications/5.2.0/clang_64/mkspecs/modules/qt_lib_svg_private.pri \
		../../../Applications/5.2.0/clang_64/mkspecs/modules/qt_lib_testlib.pri \
		../../../Applications/5.2.0/clang_64/mkspecs/modules/qt_lib_testlib_private.pri \
		../../../Applications/5.2.0/clang_64/mkspecs/modules/qt_lib_uitools.pri \
		../../../Applications/5.2.0/clang_64/mkspecs/modules/qt_lib_uitools_private.pri \
		../../../Applications/5.2.0/clang_64/mkspecs/modules/qt_lib_webkit.pri \
		../../../Applications/5.2.0/clang_64/mkspecs/modules/qt_lib_webkit_private.pri \
		../../../Applications/5.2.0/clang_64/mkspecs/modules/qt_lib_webkitwidgets.pri \
		../../../Applications/5.2.0/clang_64/mkspecs/modules/qt_lib_webkitwidgets_private.pri \
		../../../Applications/5.2.0/clang_64/mkspecs/modules/qt_lib_widgets.pri \
		../../../Applications/5.2.0/clang_64/mkspecs/modules/qt_lib_widgets_private.pri \
		../../../Applications/5.2.0/clang_64/mkspecs/modules/qt_lib_xml.pri \
		../../../Applications/5.2.0/clang_64/mkspecs/modules/qt_lib_xml_private.pri \
		../../../Applications/5.2.0/clang_64/mkspecs/modules/qt_lib_xmlpatterns.pri \
		../../../Applications/5.2.0/clang_64/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		../../../Applications/5.2.0/clang_64/mkspecs/features/qt_functions.prf \
		../../../Applications/5.2.0/clang_64/mkspecs/features/qt_config.prf \
		../../../Applications/5.2.0/clang_64/mkspecs/macx-clang/qmake.conf \
		../../../Applications/5.2.0/clang_64/mkspecs/features/spec_post.prf \
		../../../.qmake.stash \
		../../../Applications/5.2.0/clang_64/mkspecs/features/exclusive_builds.prf \
		../../../Applications/5.2.0/clang_64/mkspecs/features/default_pre.prf \
		../../../Applications/5.2.0/clang_64/mkspecs/features/mac/default_pre.prf \
		../../../Applications/5.2.0/clang_64/mkspecs/features/resolve_config.prf \
		../../../Applications/5.2.0/clang_64/mkspecs/features/default_post.prf \
		../../../Applications/5.2.0/clang_64/mkspecs/features/mac/sdk.prf \
		../../../Applications/5.2.0/clang_64/mkspecs/features/mac/default_post.prf \
		../../../Applications/5.2.0/clang_64/mkspecs/features/mac/objective_c.prf \
		../../../Applications/5.2.0/clang_64/mkspecs/features/warn_on.prf \
		../../../Applications/5.2.0/clang_64/mkspecs/features/qt.prf \
		../../../Applications/5.2.0/clang_64/mkspecs/features/resources.prf \
		../../../Applications/5.2.0/clang_64/mkspecs/features/moc.prf \
		../../../Applications/5.2.0/clang_64/mkspecs/features/unix/opengl.prf \
		../../../Applications/5.2.0/clang_64/mkspecs/features/uic.prf \
		../../../Applications/5.2.0/clang_64/mkspecs/features/unix/thread.prf \
		../../../Applications/5.2.0/clang_64/mkspecs/features/mac/rez.prf \
		../../../Applications/5.2.0/clang_64/mkspecs/features/testcase_targets.prf \
		../../../Applications/5.2.0/clang_64/mkspecs/features/exceptions.prf \
		../../../Applications/5.2.0/clang_64/mkspecs/features/yacc.prf \
		../../../Applications/5.2.0/clang_64/mkspecs/features/lex.prf \
		visorClient.pro \
		/Users/Patri/Applications/5.2.0/clang_64/lib/QtMultimediaWidgets.framework/QtMultimediaWidgets.prl \
		/Users/Patri/Applications/5.2.0/clang_64/lib/QtMultimedia.framework/QtMultimedia.prl \
		/Users/Patri/Applications/5.2.0/clang_64/lib/QtGui.framework/QtGui.prl \
		/Users/Patri/Applications/5.2.0/clang_64/lib/QtCore.framework/QtCore.prl \
		/Users/Patri/Applications/5.2.0/clang_64/lib/QtNetwork.framework/QtNetwork.prl \
		/Users/Patri/Applications/5.2.0/clang_64/lib/QtWidgets.framework/QtWidgets.prl
	$(QMAKE) -spec macx-clang CONFIG+=x86_64 -o Makefile visorClient.pro
../../../Applications/5.2.0/clang_64/mkspecs/features/spec_pre.prf:
../../../Applications/5.2.0/clang_64/mkspecs/qdevice.pri:
../../../Applications/5.2.0/clang_64/mkspecs/features/device_config.prf:
../../../Applications/5.2.0/clang_64/mkspecs/common/shell-unix.conf:
../../../Applications/5.2.0/clang_64/mkspecs/common/unix.conf:
../../../Applications/5.2.0/clang_64/mkspecs/common/mac.conf:
../../../Applications/5.2.0/clang_64/mkspecs/common/macx.conf:
../../../Applications/5.2.0/clang_64/mkspecs/common/gcc-base.conf:
../../../Applications/5.2.0/clang_64/mkspecs/common/gcc-base-mac.conf:
../../../Applications/5.2.0/clang_64/mkspecs/common/clang.conf:
../../../Applications/5.2.0/clang_64/mkspecs/common/clang-mac.conf:
../../../Applications/5.2.0/clang_64/mkspecs/qconfig.pri:
../../../Applications/5.2.0/clang_64/mkspecs/modules/qt_lib_bluetooth.pri:
../../../Applications/5.2.0/clang_64/mkspecs/modules/qt_lib_bluetooth_private.pri:
../../../Applications/5.2.0/clang_64/mkspecs/modules/qt_lib_bootstrap_private.pri:
../../../Applications/5.2.0/clang_64/mkspecs/modules/qt_lib_clucene_private.pri:
../../../Applications/5.2.0/clang_64/mkspecs/modules/qt_lib_concurrent.pri:
../../../Applications/5.2.0/clang_64/mkspecs/modules/qt_lib_concurrent_private.pri:
../../../Applications/5.2.0/clang_64/mkspecs/modules/qt_lib_core.pri:
../../../Applications/5.2.0/clang_64/mkspecs/modules/qt_lib_core_private.pri:
../../../Applications/5.2.0/clang_64/mkspecs/modules/qt_lib_declarative.pri:
../../../Applications/5.2.0/clang_64/mkspecs/modules/qt_lib_declarative_private.pri:
../../../Applications/5.2.0/clang_64/mkspecs/modules/qt_lib_designer.pri:
../../../Applications/5.2.0/clang_64/mkspecs/modules/qt_lib_designer_private.pri:
../../../Applications/5.2.0/clang_64/mkspecs/modules/qt_lib_designercomponents_private.pri:
../../../Applications/5.2.0/clang_64/mkspecs/modules/qt_lib_gui.pri:
../../../Applications/5.2.0/clang_64/mkspecs/modules/qt_lib_gui_private.pri:
../../../Applications/5.2.0/clang_64/mkspecs/modules/qt_lib_help.pri:
../../../Applications/5.2.0/clang_64/mkspecs/modules/qt_lib_help_private.pri:
../../../Applications/5.2.0/clang_64/mkspecs/modules/qt_lib_macextras.pri:
../../../Applications/5.2.0/clang_64/mkspecs/modules/qt_lib_macextras_private.pri:
../../../Applications/5.2.0/clang_64/mkspecs/modules/qt_lib_multimedia.pri:
../../../Applications/5.2.0/clang_64/mkspecs/modules/qt_lib_multimedia_private.pri:
../../../Applications/5.2.0/clang_64/mkspecs/modules/qt_lib_multimediawidgets.pri:
../../../Applications/5.2.0/clang_64/mkspecs/modules/qt_lib_multimediawidgets_private.pri:
../../../Applications/5.2.0/clang_64/mkspecs/modules/qt_lib_network.pri:
../../../Applications/5.2.0/clang_64/mkspecs/modules/qt_lib_network_private.pri:
../../../Applications/5.2.0/clang_64/mkspecs/modules/qt_lib_nfc.pri:
../../../Applications/5.2.0/clang_64/mkspecs/modules/qt_lib_nfc_private.pri:
../../../Applications/5.2.0/clang_64/mkspecs/modules/qt_lib_opengl.pri:
../../../Applications/5.2.0/clang_64/mkspecs/modules/qt_lib_opengl_private.pri:
../../../Applications/5.2.0/clang_64/mkspecs/modules/qt_lib_openglextensions.pri:
../../../Applications/5.2.0/clang_64/mkspecs/modules/qt_lib_openglextensions_private.pri:
../../../Applications/5.2.0/clang_64/mkspecs/modules/qt_lib_platformsupport_private.pri:
../../../Applications/5.2.0/clang_64/mkspecs/modules/qt_lib_positioning.pri:
../../../Applications/5.2.0/clang_64/mkspecs/modules/qt_lib_positioning_private.pri:
../../../Applications/5.2.0/clang_64/mkspecs/modules/qt_lib_printsupport.pri:
../../../Applications/5.2.0/clang_64/mkspecs/modules/qt_lib_printsupport_private.pri:
../../../Applications/5.2.0/clang_64/mkspecs/modules/qt_lib_qml.pri:
../../../Applications/5.2.0/clang_64/mkspecs/modules/qt_lib_qml_private.pri:
../../../Applications/5.2.0/clang_64/mkspecs/modules/qt_lib_qmldevtools_private.pri:
../../../Applications/5.2.0/clang_64/mkspecs/modules/qt_lib_qmltest.pri:
../../../Applications/5.2.0/clang_64/mkspecs/modules/qt_lib_qmltest_private.pri:
../../../Applications/5.2.0/clang_64/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri:
../../../Applications/5.2.0/clang_64/mkspecs/modules/qt_lib_quick.pri:
../../../Applications/5.2.0/clang_64/mkspecs/modules/qt_lib_quick_private.pri:
../../../Applications/5.2.0/clang_64/mkspecs/modules/qt_lib_quickparticles_private.pri:
../../../Applications/5.2.0/clang_64/mkspecs/modules/qt_lib_script.pri:
../../../Applications/5.2.0/clang_64/mkspecs/modules/qt_lib_script_private.pri:
../../../Applications/5.2.0/clang_64/mkspecs/modules/qt_lib_scripttools.pri:
../../../Applications/5.2.0/clang_64/mkspecs/modules/qt_lib_scripttools_private.pri:
../../../Applications/5.2.0/clang_64/mkspecs/modules/qt_lib_sensors.pri:
../../../Applications/5.2.0/clang_64/mkspecs/modules/qt_lib_sensors_private.pri:
../../../Applications/5.2.0/clang_64/mkspecs/modules/qt_lib_serialport.pri:
../../../Applications/5.2.0/clang_64/mkspecs/modules/qt_lib_serialport_private.pri:
../../../Applications/5.2.0/clang_64/mkspecs/modules/qt_lib_sql.pri:
../../../Applications/5.2.0/clang_64/mkspecs/modules/qt_lib_sql_private.pri:
../../../Applications/5.2.0/clang_64/mkspecs/modules/qt_lib_svg.pri:
../../../Applications/5.2.0/clang_64/mkspecs/modules/qt_lib_svg_private.pri:
../../../Applications/5.2.0/clang_64/mkspecs/modules/qt_lib_testlib.pri:
../../../Applications/5.2.0/clang_64/mkspecs/modules/qt_lib_testlib_private.pri:
../../../Applications/5.2.0/clang_64/mkspecs/modules/qt_lib_uitools.pri:
../../../Applications/5.2.0/clang_64/mkspecs/modules/qt_lib_uitools_private.pri:
../../../Applications/5.2.0/clang_64/mkspecs/modules/qt_lib_webkit.pri:
../../../Applications/5.2.0/clang_64/mkspecs/modules/qt_lib_webkit_private.pri:
../../../Applications/5.2.0/clang_64/mkspecs/modules/qt_lib_webkitwidgets.pri:
../../../Applications/5.2.0/clang_64/mkspecs/modules/qt_lib_webkitwidgets_private.pri:
../../../Applications/5.2.0/clang_64/mkspecs/modules/qt_lib_widgets.pri:
../../../Applications/5.2.0/clang_64/mkspecs/modules/qt_lib_widgets_private.pri:
../../../Applications/5.2.0/clang_64/mkspecs/modules/qt_lib_xml.pri:
../../../Applications/5.2.0/clang_64/mkspecs/modules/qt_lib_xml_private.pri:
../../../Applications/5.2.0/clang_64/mkspecs/modules/qt_lib_xmlpatterns.pri:
../../../Applications/5.2.0/clang_64/mkspecs/modules/qt_lib_xmlpatterns_private.pri:
../../../Applications/5.2.0/clang_64/mkspecs/features/qt_functions.prf:
../../../Applications/5.2.0/clang_64/mkspecs/features/qt_config.prf:
../../../Applications/5.2.0/clang_64/mkspecs/macx-clang/qmake.conf:
../../../Applications/5.2.0/clang_64/mkspecs/features/spec_post.prf:
../../../.qmake.stash:
../../../Applications/5.2.0/clang_64/mkspecs/features/exclusive_builds.prf:
../../../Applications/5.2.0/clang_64/mkspecs/features/default_pre.prf:
../../../Applications/5.2.0/clang_64/mkspecs/features/mac/default_pre.prf:
../../../Applications/5.2.0/clang_64/mkspecs/features/resolve_config.prf:
../../../Applications/5.2.0/clang_64/mkspecs/features/default_post.prf:
../../../Applications/5.2.0/clang_64/mkspecs/features/mac/sdk.prf:
../../../Applications/5.2.0/clang_64/mkspecs/features/mac/default_post.prf:
../../../Applications/5.2.0/clang_64/mkspecs/features/mac/objective_c.prf:
../../../Applications/5.2.0/clang_64/mkspecs/features/warn_on.prf:
../../../Applications/5.2.0/clang_64/mkspecs/features/qt.prf:
../../../Applications/5.2.0/clang_64/mkspecs/features/resources.prf:
../../../Applications/5.2.0/clang_64/mkspecs/features/moc.prf:
../../../Applications/5.2.0/clang_64/mkspecs/features/unix/opengl.prf:
../../../Applications/5.2.0/clang_64/mkspecs/features/uic.prf:
../../../Applications/5.2.0/clang_64/mkspecs/features/unix/thread.prf:
../../../Applications/5.2.0/clang_64/mkspecs/features/mac/rez.prf:
../../../Applications/5.2.0/clang_64/mkspecs/features/testcase_targets.prf:
../../../Applications/5.2.0/clang_64/mkspecs/features/exceptions.prf:
../../../Applications/5.2.0/clang_64/mkspecs/features/yacc.prf:
../../../Applications/5.2.0/clang_64/mkspecs/features/lex.prf:
visorClient.pro:
/Users/Patri/Applications/5.2.0/clang_64/lib/QtMultimediaWidgets.framework/QtMultimediaWidgets.prl:
/Users/Patri/Applications/5.2.0/clang_64/lib/QtMultimedia.framework/QtMultimedia.prl:
/Users/Patri/Applications/5.2.0/clang_64/lib/QtGui.framework/QtGui.prl:
/Users/Patri/Applications/5.2.0/clang_64/lib/QtCore.framework/QtCore.prl:
/Users/Patri/Applications/5.2.0/clang_64/lib/QtNetwork.framework/QtNetwork.prl:
/Users/Patri/Applications/5.2.0/clang_64/lib/QtWidgets.framework/QtWidgets.prl:
qmake: FORCE
	@$(QMAKE) -spec macx-clang CONFIG+=x86_64 -o Makefile visorClient.pro

qmake_all: FORCE

visor_cliente.app/Contents/PkgInfo: 
	@test -d visor_cliente.app/Contents || mkdir -p visor_cliente.app/Contents
	@$(DEL_FILE) visor_cliente.app/Contents/PkgInfo
	@echo "APPL????" >visor_cliente.app/Contents/PkgInfo
visor_cliente.app/Contents/Resources/empty.lproj: 
	@test -d visor_cliente.app/Contents/Resources || mkdir -p visor_cliente.app/Contents/Resources
	@touch visor_cliente.app/Contents/Resources/empty.lproj
	
visor_cliente.app/Contents/Info.plist: 
	@test -d visor_cliente.app/Contents || mkdir -p visor_cliente.app/Contents
	@$(DEL_FILE) visor_cliente.app/Contents/Info.plist
	@sed -e "s,@SHORT_VERSION@,1.0,g" -e "s,@TYPEINFO@,????,g" -e "s,@ICON@,,g" -e "s,@EXECUTABLE@,visor_cliente,g" -e "s,@TYPEINFO@,????,g" ../../../Applications/5.2.0/clang_64/mkspecs/macx-clang/Info.plist.app >visor_cliente.app/Contents/Info.plist
dist: 
	@test -d object/visor_cliente1.0.0 || mkdir -p object/visor_cliente1.0.0
	$(COPY_FILE) --parents $(SOURCES) $(DIST) object/visor_cliente1.0.0/ && $(COPY_FILE) --parents viewerwindow.h capturebuffer.h cvmatandqimage.h worker.h object/visor_cliente1.0.0/ && $(COPY_FILE) --parents main.cpp viewerwindow.cpp capturebuffer.cpp cvmatandqimage.cpp worker.cpp object/visor_cliente1.0.0/ && (cd `dirname object/visor_cliente1.0.0` && $(TAR) visor_cliente1.0.0.tar visor_cliente1.0.0 && $(COMPRESS) visor_cliente1.0.0.tar) && $(MOVE) `dirname object/visor_cliente1.0.0`/visor_cliente1.0.0.tar.gz . && $(DEL_FILE) -r object/visor_cliente1.0.0


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) -r visor_cliente.app
	-$(DEL_FILE) Makefile


mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

check: first

compiler_objective_c_make_all:
compiler_objective_c_clean:
compiler_rcc_make_all:
compiler_rcc_clean:
compiler_moc_header_make_all: moc/moc_viewerwindow.cpp moc/moc_capturebuffer.cpp moc/moc_worker.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc/moc_viewerwindow.cpp moc/moc_capturebuffer.cpp moc/moc_worker.cpp
moc/moc_viewerwindow.cpp: ../../../Applications/5.2.0/clang_64/lib/QtCore.framework/Versions/5/Headers/QObject \
		../../../Applications/5.2.0/clang_64/lib/QtCore.framework/Versions/5/Headers/qobject.h \
		capturebuffer.h \
		../../../Applications/5.2.0/clang_64/lib/QtMultimedia.framework/Versions/5/Headers/QAbstractVideoSurface \
		../../../Applications/5.2.0/clang_64/lib/QtMultimedia.framework/Versions/5/Headers/qabstractvideosurface.h \
		../../../Applications/5.2.0/clang_64/lib/QtGui.framework/Versions/5/Headers/QImage \
		../../../Applications/5.2.0/clang_64/lib/QtGui.framework/Versions/5/Headers/qimage.h \
		../../../Applications/5.2.0/clang_64/lib/QtMultimedia.framework/Versions/5/Headers/QVideoFrame \
		../../../Applications/5.2.0/clang_64/lib/QtMultimedia.framework/Versions/5/Headers/qvideoframe.h \
		cvmatandqimage.h \
		/usr/local/include/opencv2/core/core.hpp \
		/usr/local/include/opencv2/core/types_c.h \
		/usr/local/include/opencv2/core/version.hpp \
		/usr/local/include/opencv2/core/operations.hpp \
		/usr/local/include/opencv2/core/mat.hpp \
		worker.h \
		../../../Applications/5.2.0/clang_64/lib/QtWidgets.framework/Versions/5/Headers/QApplication \
		../../../Applications/5.2.0/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qapplication.h \
		../../../Applications/5.2.0/clang_64/lib/QtWidgets.framework/Versions/5/Headers/QMainWindow \
		../../../Applications/5.2.0/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qmainwindow.h \
		../../../Applications/5.2.0/clang_64/lib/QtCore.framework/Versions/5/Headers/QThread \
		../../../Applications/5.2.0/clang_64/lib/QtCore.framework/Versions/5/Headers/qthread.h \
		../../../Applications/5.2.0/clang_64/lib/QtWidgets.framework/Versions/5/Headers/QFileDialog \
		../../../Applications/5.2.0/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qfiledialog.h \
		../../../Applications/5.2.0/clang_64/lib/QtCore.framework/Versions/5/Headers/QFile \
		../../../Applications/5.2.0/clang_64/lib/QtCore.framework/Versions/5/Headers/qfile.h \
		../../../Applications/5.2.0/clang_64/lib/QtWidgets.framework/Versions/5/Headers/QMessageBox \
		../../../Applications/5.2.0/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qmessagebox.h \
		../../../Applications/5.2.0/clang_64/lib/QtCore.framework/Versions/5/Headers/QIODevice \
		../../../Applications/5.2.0/clang_64/lib/QtCore.framework/Versions/5/Headers/qiodevice.h \
		../../../Applications/5.2.0/clang_64/lib/QtGui.framework/Versions/5/Headers/QImageReader \
		../../../Applications/5.2.0/clang_64/lib/QtGui.framework/Versions/5/Headers/qimagereader.h \
		../../../Applications/5.2.0/clang_64/lib/QtGui.framework/Versions/5/Headers/QMovie \
		../../../Applications/5.2.0/clang_64/lib/QtGui.framework/Versions/5/Headers/qmovie.h \
		../../../Applications/5.2.0/clang_64/lib/QtCore.framework/Versions/5/Headers/QWaitCondition \
		../../../Applications/5.2.0/clang_64/lib/QtCore.framework/Versions/5/Headers/qwaitcondition.h \
		../../../Applications/5.2.0/clang_64/lib/QtCore.framework/Versions/5/Headers/QMutex \
		../../../Applications/5.2.0/clang_64/lib/QtCore.framework/Versions/5/Headers/qmutex.h \
		../../../Applications/5.2.0/clang_64/lib/QtCore.framework/Versions/5/Headers/QRect \
		../../../Applications/5.2.0/clang_64/lib/QtCore.framework/Versions/5/Headers/qrect.h \
		../../../Applications/5.2.0/clang_64/lib/QtCore.framework/Versions/5/Headers/QDebug \
		../../../Applications/5.2.0/clang_64/lib/QtCore.framework/Versions/5/Headers/qdebug.h \
		../../../Applications/5.2.0/clang_64/lib/QtGui.framework/Versions/5/Headers/QPainter \
		../../../Applications/5.2.0/clang_64/lib/QtGui.framework/Versions/5/Headers/qpainter.h \
		../../../Applications/5.2.0/clang_64/lib/QtNetwork.framework/Versions/5/Headers/QTcpSocket \
		../../../Applications/5.2.0/clang_64/lib/QtNetwork.framework/Versions/5/Headers/qtcpsocket.h \
		/usr/local/include/opencv2/video/video.hpp \
		/usr/local/include/opencv2/video/tracking.hpp \
		/usr/local/include/opencv2/imgproc/imgproc.hpp \
		/usr/local/include/opencv2/imgproc/types_c.h \
		/usr/local/include/opencv2/core/core_c.h \
		/usr/local/include/opencv2/video/background_segm.hpp \
		../../../Applications/5.2.0/clang_64/lib/QtWidgets.framework/Versions/5/Headers/QLabel \
		../../../Applications/5.2.0/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qlabel.h \
		../../../Applications/5.2.0/clang_64/lib/QtGui.framework/Versions/5/Headers/QPixmap \
		../../../Applications/5.2.0/clang_64/lib/QtGui.framework/Versions/5/Headers/qpixmap.h \
		../../../Applications/5.2.0/clang_64/lib/QtCore.framework/Versions/5/Headers/QTextStream \
		../../../Applications/5.2.0/clang_64/lib/QtCore.framework/Versions/5/Headers/qtextstream.h \
		../../../Applications/5.2.0/clang_64/lib/QtCore.framework/Versions/5/Headers/QSettings \
		../../../Applications/5.2.0/clang_64/lib/QtCore.framework/Versions/5/Headers/qsettings.h \
		../../../Applications/5.2.0/clang_64/lib/QtMultimedia.framework/Versions/5/Headers/QCamera \
		../../../Applications/5.2.0/clang_64/lib/QtMultimedia.framework/Versions/5/Headers/qcamera.h \
		../../../Applications/5.2.0/clang_64/lib/QtMultimediaWidgets.framework/Versions/5/Headers/QCameraViewfinder \
		../../../Applications/5.2.0/clang_64/lib/QtMultimediaWidgets.framework/Versions/5/Headers/qcameraviewfinder.h \
		../../../Applications/5.2.0/clang_64/lib/QtNetwork.framework/Versions/5/Headers/QtNetwork \
		../../../Applications/5.2.0/clang_64/lib/QtNetwork.framework/Versions/5/Headers/qabstractnetworkcache.h \
		../../../Applications/5.2.0/clang_64/lib/QtNetwork.framework/Versions/5/Headers/qhttpmultipart.h \
		../../../Applications/5.2.0/clang_64/lib/QtNetwork.framework/Versions/5/Headers/qnetworkaccessmanager.h \
		../../../Applications/5.2.0/clang_64/lib/QtNetwork.framework/Versions/5/Headers/qnetworkcookie.h \
		../../../Applications/5.2.0/clang_64/lib/QtNetwork.framework/Versions/5/Headers/qnetworkcookiejar.h \
		../../../Applications/5.2.0/clang_64/lib/QtNetwork.framework/Versions/5/Headers/qnetworkdiskcache.h \
		../../../Applications/5.2.0/clang_64/lib/QtNetwork.framework/Versions/5/Headers/qnetworkreply.h \
		../../../Applications/5.2.0/clang_64/lib/QtNetwork.framework/Versions/5/Headers/qnetworkrequest.h \
		../../../Applications/5.2.0/clang_64/lib/QtNetwork.framework/Versions/5/Headers/qnetworkconfigmanager.h \
		../../../Applications/5.2.0/clang_64/lib/QtNetwork.framework/Versions/5/Headers/qnetworkconfiguration.h \
		../../../Applications/5.2.0/clang_64/lib/QtNetwork.framework/Versions/5/Headers/qnetworksession.h \
		../../../Applications/5.2.0/clang_64/lib/QtNetwork.framework/Versions/5/Headers/qauthenticator.h \
		../../../Applications/5.2.0/clang_64/lib/QtNetwork.framework/Versions/5/Headers/qdnslookup.h \
		../../../Applications/5.2.0/clang_64/lib/QtNetwork.framework/Versions/5/Headers/qhostaddress.h \
		../../../Applications/5.2.0/clang_64/lib/QtNetwork.framework/Versions/5/Headers/qhostinfo.h \
		../../../Applications/5.2.0/clang_64/lib/QtNetwork.framework/Versions/5/Headers/qnetworkinterface.h \
		../../../Applications/5.2.0/clang_64/lib/QtNetwork.framework/Versions/5/Headers/qnetworkproxy.h \
		../../../Applications/5.2.0/clang_64/lib/QtNetwork.framework/Versions/5/Headers/qabstractsocket.h \
		../../../Applications/5.2.0/clang_64/lib/QtNetwork.framework/Versions/5/Headers/qlocalserver.h \
		../../../Applications/5.2.0/clang_64/lib/QtNetwork.framework/Versions/5/Headers/qlocalsocket.h \
		../../../Applications/5.2.0/clang_64/lib/QtNetwork.framework/Versions/5/Headers/qtcpserver.h \
		../../../Applications/5.2.0/clang_64/lib/QtNetwork.framework/Versions/5/Headers/qudpsocket.h \
		../../../Applications/5.2.0/clang_64/lib/QtNetwork.framework/Versions/5/Headers/qssl.h \
		../../../Applications/5.2.0/clang_64/lib/QtNetwork.framework/Versions/5/Headers/qsslcertificate.h \
		../../../Applications/5.2.0/clang_64/lib/QtNetwork.framework/Versions/5/Headers/qsslcertificateextension.h \
		../../../Applications/5.2.0/clang_64/lib/QtNetwork.framework/Versions/5/Headers/qsslcipher.h \
		../../../Applications/5.2.0/clang_64/lib/QtNetwork.framework/Versions/5/Headers/qsslconfiguration.h \
		../../../Applications/5.2.0/clang_64/lib/QtNetwork.framework/Versions/5/Headers/qsslerror.h \
		../../../Applications/5.2.0/clang_64/lib/QtNetwork.framework/Versions/5/Headers/qsslkey.h \
		../../../Applications/5.2.0/clang_64/lib/QtNetwork.framework/Versions/5/Headers/qsslsocket.h \
		../../../Applications/5.2.0/clang_64/lib/QtNetwork.framework/Versions/5/Headers/qtnetworkversion.h \
		../../../Applications/5.2.0/clang_64/lib/QtCore.framework/Versions/5/Headers/QTimer \
		../../../Applications/5.2.0/clang_64/lib/QtCore.framework/Versions/5/Headers/qtimer.h \
		../../../Applications/5.2.0/clang_64/lib/QtWidgets.framework/Versions/5/Headers/QDialog \
		../../../Applications/5.2.0/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qdialog.h \
		../../../Applications/5.2.0/clang_64/lib/QtCore.framework/Versions/5/Headers/QSocketNotifier \
		../../../Applications/5.2.0/clang_64/lib/QtCore.framework/Versions/5/Headers/qsocketnotifier.h \
		viewerwindow.h
	/Users/Patri/Applications/5.2.0/clang_64/bin/moc $(DEFINES) -D__APPLE__ -D__GNUC__=4 $(INCPATH) viewerwindow.h -o moc/moc_viewerwindow.cpp

moc/moc_capturebuffer.cpp: ../../../Applications/5.2.0/clang_64/lib/QtMultimedia.framework/Versions/5/Headers/QAbstractVideoSurface \
		../../../Applications/5.2.0/clang_64/lib/QtMultimedia.framework/Versions/5/Headers/qabstractvideosurface.h \
		../../../Applications/5.2.0/clang_64/lib/QtGui.framework/Versions/5/Headers/QImage \
		../../../Applications/5.2.0/clang_64/lib/QtGui.framework/Versions/5/Headers/qimage.h \
		../../../Applications/5.2.0/clang_64/lib/QtMultimedia.framework/Versions/5/Headers/QVideoFrame \
		../../../Applications/5.2.0/clang_64/lib/QtMultimedia.framework/Versions/5/Headers/qvideoframe.h \
		capturebuffer.h
	/Users/Patri/Applications/5.2.0/clang_64/bin/moc $(DEFINES) -D__APPLE__ -D__GNUC__=4 $(INCPATH) capturebuffer.h -o moc/moc_capturebuffer.cpp

moc/moc_worker.cpp: ../../../Applications/5.2.0/clang_64/lib/QtWidgets.framework/Versions/5/Headers/QApplication \
		../../../Applications/5.2.0/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qapplication.h \
		../../../Applications/5.2.0/clang_64/lib/QtWidgets.framework/Versions/5/Headers/QMainWindow \
		../../../Applications/5.2.0/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qmainwindow.h \
		../../../Applications/5.2.0/clang_64/lib/QtCore.framework/Versions/5/Headers/QThread \
		../../../Applications/5.2.0/clang_64/lib/QtCore.framework/Versions/5/Headers/qthread.h \
		../../../Applications/5.2.0/clang_64/lib/QtWidgets.framework/Versions/5/Headers/QFileDialog \
		../../../Applications/5.2.0/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qfiledialog.h \
		../../../Applications/5.2.0/clang_64/lib/QtCore.framework/Versions/5/Headers/QFile \
		../../../Applications/5.2.0/clang_64/lib/QtCore.framework/Versions/5/Headers/qfile.h \
		../../../Applications/5.2.0/clang_64/lib/QtWidgets.framework/Versions/5/Headers/QMessageBox \
		../../../Applications/5.2.0/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qmessagebox.h \
		../../../Applications/5.2.0/clang_64/lib/QtCore.framework/Versions/5/Headers/QIODevice \
		../../../Applications/5.2.0/clang_64/lib/QtCore.framework/Versions/5/Headers/qiodevice.h \
		../../../Applications/5.2.0/clang_64/lib/QtGui.framework/Versions/5/Headers/QImageReader \
		../../../Applications/5.2.0/clang_64/lib/QtGui.framework/Versions/5/Headers/qimagereader.h \
		../../../Applications/5.2.0/clang_64/lib/QtGui.framework/Versions/5/Headers/QMovie \
		../../../Applications/5.2.0/clang_64/lib/QtGui.framework/Versions/5/Headers/qmovie.h \
		../../../Applications/5.2.0/clang_64/lib/QtCore.framework/Versions/5/Headers/QWaitCondition \
		../../../Applications/5.2.0/clang_64/lib/QtCore.framework/Versions/5/Headers/qwaitcondition.h \
		../../../Applications/5.2.0/clang_64/lib/QtCore.framework/Versions/5/Headers/QMutex \
		../../../Applications/5.2.0/clang_64/lib/QtCore.framework/Versions/5/Headers/qmutex.h \
		../../../Applications/5.2.0/clang_64/lib/QtCore.framework/Versions/5/Headers/QRect \
		../../../Applications/5.2.0/clang_64/lib/QtCore.framework/Versions/5/Headers/qrect.h \
		../../../Applications/5.2.0/clang_64/lib/QtCore.framework/Versions/5/Headers/QDebug \
		../../../Applications/5.2.0/clang_64/lib/QtCore.framework/Versions/5/Headers/qdebug.h \
		../../../Applications/5.2.0/clang_64/lib/QtGui.framework/Versions/5/Headers/QPainter \
		../../../Applications/5.2.0/clang_64/lib/QtGui.framework/Versions/5/Headers/qpainter.h \
		../../../Applications/5.2.0/clang_64/lib/QtNetwork.framework/Versions/5/Headers/QTcpSocket \
		../../../Applications/5.2.0/clang_64/lib/QtNetwork.framework/Versions/5/Headers/qtcpsocket.h \
		/usr/local/include/opencv2/core/core.hpp \
		/usr/local/include/opencv2/core/types_c.h \
		/usr/local/include/opencv2/core/version.hpp \
		/usr/local/include/opencv2/core/operations.hpp \
		/usr/local/include/opencv2/core/mat.hpp \
		/usr/local/include/opencv2/video/video.hpp \
		/usr/local/include/opencv2/video/tracking.hpp \
		/usr/local/include/opencv2/imgproc/imgproc.hpp \
		/usr/local/include/opencv2/imgproc/types_c.h \
		/usr/local/include/opencv2/core/core_c.h \
		/usr/local/include/opencv2/video/background_segm.hpp \
		cvmatandqimage.h \
		../../../Applications/5.2.0/clang_64/lib/QtGui.framework/Versions/5/Headers/QImage \
		../../../Applications/5.2.0/clang_64/lib/QtGui.framework/Versions/5/Headers/qimage.h \
		worker.h
	/Users/Patri/Applications/5.2.0/clang_64/bin/moc $(DEFINES) -D__APPLE__ -D__GNUC__=4 $(INCPATH) worker.h -o moc/moc_worker.cpp

compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all:
compiler_uic_clean:
compiler_rez_source_make_all:
compiler_rez_source_clean:
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_header_clean 

####### Compile

object/main.o: main.cpp viewerwindow.h \
		../../../Applications/5.2.0/clang_64/lib/QtCore.framework/Versions/5/Headers/QObject \
		../../../Applications/5.2.0/clang_64/lib/QtCore.framework/Versions/5/Headers/qobject.h \
		capturebuffer.h \
		../../../Applications/5.2.0/clang_64/lib/QtMultimedia.framework/Versions/5/Headers/QAbstractVideoSurface \
		../../../Applications/5.2.0/clang_64/lib/QtMultimedia.framework/Versions/5/Headers/qabstractvideosurface.h \
		../../../Applications/5.2.0/clang_64/lib/QtGui.framework/Versions/5/Headers/QImage \
		../../../Applications/5.2.0/clang_64/lib/QtGui.framework/Versions/5/Headers/qimage.h \
		../../../Applications/5.2.0/clang_64/lib/QtMultimedia.framework/Versions/5/Headers/QVideoFrame \
		../../../Applications/5.2.0/clang_64/lib/QtMultimedia.framework/Versions/5/Headers/qvideoframe.h \
		cvmatandqimage.h \
		/usr/local/include/opencv2/core/core.hpp \
		/usr/local/include/opencv2/core/types_c.h \
		/usr/local/include/opencv2/core/version.hpp \
		/usr/local/include/opencv2/core/operations.hpp \
		/usr/local/include/opencv2/core/mat.hpp \
		worker.h \
		../../../Applications/5.2.0/clang_64/lib/QtWidgets.framework/Versions/5/Headers/QApplication \
		../../../Applications/5.2.0/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qapplication.h \
		../../../Applications/5.2.0/clang_64/lib/QtWidgets.framework/Versions/5/Headers/QMainWindow \
		../../../Applications/5.2.0/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qmainwindow.h \
		../../../Applications/5.2.0/clang_64/lib/QtCore.framework/Versions/5/Headers/QThread \
		../../../Applications/5.2.0/clang_64/lib/QtCore.framework/Versions/5/Headers/qthread.h \
		../../../Applications/5.2.0/clang_64/lib/QtWidgets.framework/Versions/5/Headers/QFileDialog \
		../../../Applications/5.2.0/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qfiledialog.h \
		../../../Applications/5.2.0/clang_64/lib/QtCore.framework/Versions/5/Headers/QFile \
		../../../Applications/5.2.0/clang_64/lib/QtCore.framework/Versions/5/Headers/qfile.h \
		../../../Applications/5.2.0/clang_64/lib/QtWidgets.framework/Versions/5/Headers/QMessageBox \
		../../../Applications/5.2.0/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qmessagebox.h \
		../../../Applications/5.2.0/clang_64/lib/QtCore.framework/Versions/5/Headers/QIODevice \
		../../../Applications/5.2.0/clang_64/lib/QtCore.framework/Versions/5/Headers/qiodevice.h \
		../../../Applications/5.2.0/clang_64/lib/QtGui.framework/Versions/5/Headers/QImageReader \
		../../../Applications/5.2.0/clang_64/lib/QtGui.framework/Versions/5/Headers/qimagereader.h \
		../../../Applications/5.2.0/clang_64/lib/QtGui.framework/Versions/5/Headers/QMovie \
		../../../Applications/5.2.0/clang_64/lib/QtGui.framework/Versions/5/Headers/qmovie.h \
		../../../Applications/5.2.0/clang_64/lib/QtCore.framework/Versions/5/Headers/QWaitCondition \
		../../../Applications/5.2.0/clang_64/lib/QtCore.framework/Versions/5/Headers/qwaitcondition.h \
		../../../Applications/5.2.0/clang_64/lib/QtCore.framework/Versions/5/Headers/QMutex \
		../../../Applications/5.2.0/clang_64/lib/QtCore.framework/Versions/5/Headers/qmutex.h \
		../../../Applications/5.2.0/clang_64/lib/QtCore.framework/Versions/5/Headers/QRect \
		../../../Applications/5.2.0/clang_64/lib/QtCore.framework/Versions/5/Headers/qrect.h \
		../../../Applications/5.2.0/clang_64/lib/QtCore.framework/Versions/5/Headers/QDebug \
		../../../Applications/5.2.0/clang_64/lib/QtCore.framework/Versions/5/Headers/qdebug.h \
		../../../Applications/5.2.0/clang_64/lib/QtGui.framework/Versions/5/Headers/QPainter \
		../../../Applications/5.2.0/clang_64/lib/QtGui.framework/Versions/5/Headers/qpainter.h \
		../../../Applications/5.2.0/clang_64/lib/QtNetwork.framework/Versions/5/Headers/QTcpSocket \
		../../../Applications/5.2.0/clang_64/lib/QtNetwork.framework/Versions/5/Headers/qtcpsocket.h \
		/usr/local/include/opencv2/video/video.hpp \
		/usr/local/include/opencv2/video/tracking.hpp \
		/usr/local/include/opencv2/imgproc/imgproc.hpp \
		/usr/local/include/opencv2/imgproc/types_c.h \
		/usr/local/include/opencv2/core/core_c.h \
		/usr/local/include/opencv2/video/background_segm.hpp \
		../../../Applications/5.2.0/clang_64/lib/QtWidgets.framework/Versions/5/Headers/QLabel \
		../../../Applications/5.2.0/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qlabel.h \
		../../../Applications/5.2.0/clang_64/lib/QtGui.framework/Versions/5/Headers/QPixmap \
		../../../Applications/5.2.0/clang_64/lib/QtGui.framework/Versions/5/Headers/qpixmap.h \
		../../../Applications/5.2.0/clang_64/lib/QtCore.framework/Versions/5/Headers/QTextStream \
		../../../Applications/5.2.0/clang_64/lib/QtCore.framework/Versions/5/Headers/qtextstream.h \
		../../../Applications/5.2.0/clang_64/lib/QtCore.framework/Versions/5/Headers/QSettings \
		../../../Applications/5.2.0/clang_64/lib/QtCore.framework/Versions/5/Headers/qsettings.h \
		../../../Applications/5.2.0/clang_64/lib/QtMultimedia.framework/Versions/5/Headers/QCamera \
		../../../Applications/5.2.0/clang_64/lib/QtMultimedia.framework/Versions/5/Headers/qcamera.h \
		../../../Applications/5.2.0/clang_64/lib/QtMultimediaWidgets.framework/Versions/5/Headers/QCameraViewfinder \
		../../../Applications/5.2.0/clang_64/lib/QtMultimediaWidgets.framework/Versions/5/Headers/qcameraviewfinder.h \
		../../../Applications/5.2.0/clang_64/lib/QtNetwork.framework/Versions/5/Headers/QtNetwork \
		../../../Applications/5.2.0/clang_64/lib/QtNetwork.framework/Versions/5/Headers/qabstractnetworkcache.h \
		../../../Applications/5.2.0/clang_64/lib/QtNetwork.framework/Versions/5/Headers/qhttpmultipart.h \
		../../../Applications/5.2.0/clang_64/lib/QtNetwork.framework/Versions/5/Headers/qnetworkaccessmanager.h \
		../../../Applications/5.2.0/clang_64/lib/QtNetwork.framework/Versions/5/Headers/qnetworkcookie.h \
		../../../Applications/5.2.0/clang_64/lib/QtNetwork.framework/Versions/5/Headers/qnetworkcookiejar.h \
		../../../Applications/5.2.0/clang_64/lib/QtNetwork.framework/Versions/5/Headers/qnetworkdiskcache.h \
		../../../Applications/5.2.0/clang_64/lib/QtNetwork.framework/Versions/5/Headers/qnetworkreply.h \
		../../../Applications/5.2.0/clang_64/lib/QtNetwork.framework/Versions/5/Headers/qnetworkrequest.h \
		../../../Applications/5.2.0/clang_64/lib/QtNetwork.framework/Versions/5/Headers/qnetworkconfigmanager.h \
		../../../Applications/5.2.0/clang_64/lib/QtNetwork.framework/Versions/5/Headers/qnetworkconfiguration.h \
		../../../Applications/5.2.0/clang_64/lib/QtNetwork.framework/Versions/5/Headers/qnetworksession.h \
		../../../Applications/5.2.0/clang_64/lib/QtNetwork.framework/Versions/5/Headers/qauthenticator.h \
		../../../Applications/5.2.0/clang_64/lib/QtNetwork.framework/Versions/5/Headers/qdnslookup.h \
		../../../Applications/5.2.0/clang_64/lib/QtNetwork.framework/Versions/5/Headers/qhostaddress.h \
		../../../Applications/5.2.0/clang_64/lib/QtNetwork.framework/Versions/5/Headers/qhostinfo.h \
		../../../Applications/5.2.0/clang_64/lib/QtNetwork.framework/Versions/5/Headers/qnetworkinterface.h \
		../../../Applications/5.2.0/clang_64/lib/QtNetwork.framework/Versions/5/Headers/qnetworkproxy.h \
		../../../Applications/5.2.0/clang_64/lib/QtNetwork.framework/Versions/5/Headers/qabstractsocket.h \
		../../../Applications/5.2.0/clang_64/lib/QtNetwork.framework/Versions/5/Headers/qlocalserver.h \
		../../../Applications/5.2.0/clang_64/lib/QtNetwork.framework/Versions/5/Headers/qlocalsocket.h \
		../../../Applications/5.2.0/clang_64/lib/QtNetwork.framework/Versions/5/Headers/qtcpserver.h \
		../../../Applications/5.2.0/clang_64/lib/QtNetwork.framework/Versions/5/Headers/qudpsocket.h \
		../../../Applications/5.2.0/clang_64/lib/QtNetwork.framework/Versions/5/Headers/qssl.h \
		../../../Applications/5.2.0/clang_64/lib/QtNetwork.framework/Versions/5/Headers/qsslcertificate.h \
		../../../Applications/5.2.0/clang_64/lib/QtNetwork.framework/Versions/5/Headers/qsslcertificateextension.h \
		../../../Applications/5.2.0/clang_64/lib/QtNetwork.framework/Versions/5/Headers/qsslcipher.h \
		../../../Applications/5.2.0/clang_64/lib/QtNetwork.framework/Versions/5/Headers/qsslconfiguration.h \
		../../../Applications/5.2.0/clang_64/lib/QtNetwork.framework/Versions/5/Headers/qsslerror.h \
		../../../Applications/5.2.0/clang_64/lib/QtNetwork.framework/Versions/5/Headers/qsslkey.h \
		../../../Applications/5.2.0/clang_64/lib/QtNetwork.framework/Versions/5/Headers/qsslsocket.h \
		../../../Applications/5.2.0/clang_64/lib/QtNetwork.framework/Versions/5/Headers/qtnetworkversion.h \
		../../../Applications/5.2.0/clang_64/lib/QtCore.framework/Versions/5/Headers/QTimer \
		../../../Applications/5.2.0/clang_64/lib/QtCore.framework/Versions/5/Headers/qtimer.h \
		../../../Applications/5.2.0/clang_64/lib/QtWidgets.framework/Versions/5/Headers/QDialog \
		../../../Applications/5.2.0/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qdialog.h \
		../../../Applications/5.2.0/clang_64/lib/QtCore.framework/Versions/5/Headers/QSocketNotifier \
		../../../Applications/5.2.0/clang_64/lib/QtCore.framework/Versions/5/Headers/qsocketnotifier.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o object/main.o main.cpp

object/viewerwindow.o: viewerwindow.cpp viewerwindow.h \
		../../../Applications/5.2.0/clang_64/lib/QtCore.framework/Versions/5/Headers/QObject \
		../../../Applications/5.2.0/clang_64/lib/QtCore.framework/Versions/5/Headers/qobject.h \
		capturebuffer.h \
		../../../Applications/5.2.0/clang_64/lib/QtMultimedia.framework/Versions/5/Headers/QAbstractVideoSurface \
		../../../Applications/5.2.0/clang_64/lib/QtMultimedia.framework/Versions/5/Headers/qabstractvideosurface.h \
		../../../Applications/5.2.0/clang_64/lib/QtGui.framework/Versions/5/Headers/QImage \
		../../../Applications/5.2.0/clang_64/lib/QtGui.framework/Versions/5/Headers/qimage.h \
		../../../Applications/5.2.0/clang_64/lib/QtMultimedia.framework/Versions/5/Headers/QVideoFrame \
		../../../Applications/5.2.0/clang_64/lib/QtMultimedia.framework/Versions/5/Headers/qvideoframe.h \
		cvmatandqimage.h \
		/usr/local/include/opencv2/core/core.hpp \
		/usr/local/include/opencv2/core/types_c.h \
		/usr/local/include/opencv2/core/version.hpp \
		/usr/local/include/opencv2/core/operations.hpp \
		/usr/local/include/opencv2/core/mat.hpp \
		worker.h \
		../../../Applications/5.2.0/clang_64/lib/QtWidgets.framework/Versions/5/Headers/QApplication \
		../../../Applications/5.2.0/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qapplication.h \
		../../../Applications/5.2.0/clang_64/lib/QtWidgets.framework/Versions/5/Headers/QMainWindow \
		../../../Applications/5.2.0/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qmainwindow.h \
		../../../Applications/5.2.0/clang_64/lib/QtCore.framework/Versions/5/Headers/QThread \
		../../../Applications/5.2.0/clang_64/lib/QtCore.framework/Versions/5/Headers/qthread.h \
		../../../Applications/5.2.0/clang_64/lib/QtWidgets.framework/Versions/5/Headers/QFileDialog \
		../../../Applications/5.2.0/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qfiledialog.h \
		../../../Applications/5.2.0/clang_64/lib/QtCore.framework/Versions/5/Headers/QFile \
		../../../Applications/5.2.0/clang_64/lib/QtCore.framework/Versions/5/Headers/qfile.h \
		../../../Applications/5.2.0/clang_64/lib/QtWidgets.framework/Versions/5/Headers/QMessageBox \
		../../../Applications/5.2.0/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qmessagebox.h \
		../../../Applications/5.2.0/clang_64/lib/QtCore.framework/Versions/5/Headers/QIODevice \
		../../../Applications/5.2.0/clang_64/lib/QtCore.framework/Versions/5/Headers/qiodevice.h \
		../../../Applications/5.2.0/clang_64/lib/QtGui.framework/Versions/5/Headers/QImageReader \
		../../../Applications/5.2.0/clang_64/lib/QtGui.framework/Versions/5/Headers/qimagereader.h \
		../../../Applications/5.2.0/clang_64/lib/QtGui.framework/Versions/5/Headers/QMovie \
		../../../Applications/5.2.0/clang_64/lib/QtGui.framework/Versions/5/Headers/qmovie.h \
		../../../Applications/5.2.0/clang_64/lib/QtCore.framework/Versions/5/Headers/QWaitCondition \
		../../../Applications/5.2.0/clang_64/lib/QtCore.framework/Versions/5/Headers/qwaitcondition.h \
		../../../Applications/5.2.0/clang_64/lib/QtCore.framework/Versions/5/Headers/QMutex \
		../../../Applications/5.2.0/clang_64/lib/QtCore.framework/Versions/5/Headers/qmutex.h \
		../../../Applications/5.2.0/clang_64/lib/QtCore.framework/Versions/5/Headers/QRect \
		../../../Applications/5.2.0/clang_64/lib/QtCore.framework/Versions/5/Headers/qrect.h \
		../../../Applications/5.2.0/clang_64/lib/QtCore.framework/Versions/5/Headers/QDebug \
		../../../Applications/5.2.0/clang_64/lib/QtCore.framework/Versions/5/Headers/qdebug.h \
		../../../Applications/5.2.0/clang_64/lib/QtGui.framework/Versions/5/Headers/QPainter \
		../../../Applications/5.2.0/clang_64/lib/QtGui.framework/Versions/5/Headers/qpainter.h \
		../../../Applications/5.2.0/clang_64/lib/QtNetwork.framework/Versions/5/Headers/QTcpSocket \
		../../../Applications/5.2.0/clang_64/lib/QtNetwork.framework/Versions/5/Headers/qtcpsocket.h \
		/usr/local/include/opencv2/video/video.hpp \
		/usr/local/include/opencv2/video/tracking.hpp \
		/usr/local/include/opencv2/imgproc/imgproc.hpp \
		/usr/local/include/opencv2/imgproc/types_c.h \
		/usr/local/include/opencv2/core/core_c.h \
		/usr/local/include/opencv2/video/background_segm.hpp \
		../../../Applications/5.2.0/clang_64/lib/QtWidgets.framework/Versions/5/Headers/QLabel \
		../../../Applications/5.2.0/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qlabel.h \
		../../../Applications/5.2.0/clang_64/lib/QtGui.framework/Versions/5/Headers/QPixmap \
		../../../Applications/5.2.0/clang_64/lib/QtGui.framework/Versions/5/Headers/qpixmap.h \
		../../../Applications/5.2.0/clang_64/lib/QtCore.framework/Versions/5/Headers/QTextStream \
		../../../Applications/5.2.0/clang_64/lib/QtCore.framework/Versions/5/Headers/qtextstream.h \
		../../../Applications/5.2.0/clang_64/lib/QtCore.framework/Versions/5/Headers/QSettings \
		../../../Applications/5.2.0/clang_64/lib/QtCore.framework/Versions/5/Headers/qsettings.h \
		../../../Applications/5.2.0/clang_64/lib/QtMultimedia.framework/Versions/5/Headers/QCamera \
		../../../Applications/5.2.0/clang_64/lib/QtMultimedia.framework/Versions/5/Headers/qcamera.h \
		../../../Applications/5.2.0/clang_64/lib/QtMultimediaWidgets.framework/Versions/5/Headers/QCameraViewfinder \
		../../../Applications/5.2.0/clang_64/lib/QtMultimediaWidgets.framework/Versions/5/Headers/qcameraviewfinder.h \
		../../../Applications/5.2.0/clang_64/lib/QtNetwork.framework/Versions/5/Headers/QtNetwork \
		../../../Applications/5.2.0/clang_64/lib/QtNetwork.framework/Versions/5/Headers/qabstractnetworkcache.h \
		../../../Applications/5.2.0/clang_64/lib/QtNetwork.framework/Versions/5/Headers/qhttpmultipart.h \
		../../../Applications/5.2.0/clang_64/lib/QtNetwork.framework/Versions/5/Headers/qnetworkaccessmanager.h \
		../../../Applications/5.2.0/clang_64/lib/QtNetwork.framework/Versions/5/Headers/qnetworkcookie.h \
		../../../Applications/5.2.0/clang_64/lib/QtNetwork.framework/Versions/5/Headers/qnetworkcookiejar.h \
		../../../Applications/5.2.0/clang_64/lib/QtNetwork.framework/Versions/5/Headers/qnetworkdiskcache.h \
		../../../Applications/5.2.0/clang_64/lib/QtNetwork.framework/Versions/5/Headers/qnetworkreply.h \
		../../../Applications/5.2.0/clang_64/lib/QtNetwork.framework/Versions/5/Headers/qnetworkrequest.h \
		../../../Applications/5.2.0/clang_64/lib/QtNetwork.framework/Versions/5/Headers/qnetworkconfigmanager.h \
		../../../Applications/5.2.0/clang_64/lib/QtNetwork.framework/Versions/5/Headers/qnetworkconfiguration.h \
		../../../Applications/5.2.0/clang_64/lib/QtNetwork.framework/Versions/5/Headers/qnetworksession.h \
		../../../Applications/5.2.0/clang_64/lib/QtNetwork.framework/Versions/5/Headers/qauthenticator.h \
		../../../Applications/5.2.0/clang_64/lib/QtNetwork.framework/Versions/5/Headers/qdnslookup.h \
		../../../Applications/5.2.0/clang_64/lib/QtNetwork.framework/Versions/5/Headers/qhostaddress.h \
		../../../Applications/5.2.0/clang_64/lib/QtNetwork.framework/Versions/5/Headers/qhostinfo.h \
		../../../Applications/5.2.0/clang_64/lib/QtNetwork.framework/Versions/5/Headers/qnetworkinterface.h \
		../../../Applications/5.2.0/clang_64/lib/QtNetwork.framework/Versions/5/Headers/qnetworkproxy.h \
		../../../Applications/5.2.0/clang_64/lib/QtNetwork.framework/Versions/5/Headers/qabstractsocket.h \
		../../../Applications/5.2.0/clang_64/lib/QtNetwork.framework/Versions/5/Headers/qlocalserver.h \
		../../../Applications/5.2.0/clang_64/lib/QtNetwork.framework/Versions/5/Headers/qlocalsocket.h \
		../../../Applications/5.2.0/clang_64/lib/QtNetwork.framework/Versions/5/Headers/qtcpserver.h \
		../../../Applications/5.2.0/clang_64/lib/QtNetwork.framework/Versions/5/Headers/qudpsocket.h \
		../../../Applications/5.2.0/clang_64/lib/QtNetwork.framework/Versions/5/Headers/qssl.h \
		../../../Applications/5.2.0/clang_64/lib/QtNetwork.framework/Versions/5/Headers/qsslcertificate.h \
		../../../Applications/5.2.0/clang_64/lib/QtNetwork.framework/Versions/5/Headers/qsslcertificateextension.h \
		../../../Applications/5.2.0/clang_64/lib/QtNetwork.framework/Versions/5/Headers/qsslcipher.h \
		../../../Applications/5.2.0/clang_64/lib/QtNetwork.framework/Versions/5/Headers/qsslconfiguration.h \
		../../../Applications/5.2.0/clang_64/lib/QtNetwork.framework/Versions/5/Headers/qsslerror.h \
		../../../Applications/5.2.0/clang_64/lib/QtNetwork.framework/Versions/5/Headers/qsslkey.h \
		../../../Applications/5.2.0/clang_64/lib/QtNetwork.framework/Versions/5/Headers/qsslsocket.h \
		../../../Applications/5.2.0/clang_64/lib/QtNetwork.framework/Versions/5/Headers/qtnetworkversion.h \
		../../../Applications/5.2.0/clang_64/lib/QtCore.framework/Versions/5/Headers/QTimer \
		../../../Applications/5.2.0/clang_64/lib/QtCore.framework/Versions/5/Headers/qtimer.h \
		../../../Applications/5.2.0/clang_64/lib/QtWidgets.framework/Versions/5/Headers/QDialog \
		../../../Applications/5.2.0/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qdialog.h \
		../../../Applications/5.2.0/clang_64/lib/QtCore.framework/Versions/5/Headers/QSocketNotifier \
		../../../Applications/5.2.0/clang_64/lib/QtCore.framework/Versions/5/Headers/qsocketnotifier.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o object/viewerwindow.o viewerwindow.cpp

object/capturebuffer.o: capturebuffer.cpp capturebuffer.h \
		../../../Applications/5.2.0/clang_64/lib/QtMultimedia.framework/Versions/5/Headers/QAbstractVideoSurface \
		../../../Applications/5.2.0/clang_64/lib/QtMultimedia.framework/Versions/5/Headers/qabstractvideosurface.h \
		../../../Applications/5.2.0/clang_64/lib/QtGui.framework/Versions/5/Headers/QImage \
		../../../Applications/5.2.0/clang_64/lib/QtGui.framework/Versions/5/Headers/qimage.h \
		../../../Applications/5.2.0/clang_64/lib/QtMultimedia.framework/Versions/5/Headers/QVideoFrame \
		../../../Applications/5.2.0/clang_64/lib/QtMultimedia.framework/Versions/5/Headers/qvideoframe.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o object/capturebuffer.o capturebuffer.cpp

object/cvmatandqimage.o: cvmatandqimage.cpp cvmatandqimage.h \
		../../../Applications/5.2.0/clang_64/lib/QtGui.framework/Versions/5/Headers/QImage \
		../../../Applications/5.2.0/clang_64/lib/QtGui.framework/Versions/5/Headers/qimage.h \
		/usr/local/include/opencv2/core/core.hpp \
		/usr/local/include/opencv2/core/types_c.h \
		/usr/local/include/opencv2/core/version.hpp \
		/usr/local/include/opencv2/core/operations.hpp \
		/usr/local/include/opencv2/core/mat.hpp \
		../../../Applications/5.2.0/clang_64/lib/QtCore.framework/Versions/5/Headers/QSysInfo \
		../../../Applications/5.2.0/clang_64/lib/QtCore.framework/Versions/5/Headers/qsysinfo.h \
		../../../Applications/5.2.0/clang_64/lib/QtCore.framework/Versions/5/Headers/QDebug \
		../../../Applications/5.2.0/clang_64/lib/QtCore.framework/Versions/5/Headers/qdebug.h \
		/usr/local/include/opencv2/imgproc/imgproc.hpp \
		/usr/local/include/opencv2/imgproc/types_c.h \
		/usr/local/include/opencv2/core/core_c.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o object/cvmatandqimage.o cvmatandqimage.cpp

object/worker.o: worker.cpp worker.h \
		../../../Applications/5.2.0/clang_64/lib/QtWidgets.framework/Versions/5/Headers/QApplication \
		../../../Applications/5.2.0/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qapplication.h \
		../../../Applications/5.2.0/clang_64/lib/QtWidgets.framework/Versions/5/Headers/QMainWindow \
		../../../Applications/5.2.0/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qmainwindow.h \
		../../../Applications/5.2.0/clang_64/lib/QtCore.framework/Versions/5/Headers/QThread \
		../../../Applications/5.2.0/clang_64/lib/QtCore.framework/Versions/5/Headers/qthread.h \
		../../../Applications/5.2.0/clang_64/lib/QtWidgets.framework/Versions/5/Headers/QFileDialog \
		../../../Applications/5.2.0/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qfiledialog.h \
		../../../Applications/5.2.0/clang_64/lib/QtCore.framework/Versions/5/Headers/QFile \
		../../../Applications/5.2.0/clang_64/lib/QtCore.framework/Versions/5/Headers/qfile.h \
		../../../Applications/5.2.0/clang_64/lib/QtWidgets.framework/Versions/5/Headers/QMessageBox \
		../../../Applications/5.2.0/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qmessagebox.h \
		../../../Applications/5.2.0/clang_64/lib/QtCore.framework/Versions/5/Headers/QIODevice \
		../../../Applications/5.2.0/clang_64/lib/QtCore.framework/Versions/5/Headers/qiodevice.h \
		../../../Applications/5.2.0/clang_64/lib/QtGui.framework/Versions/5/Headers/QImageReader \
		../../../Applications/5.2.0/clang_64/lib/QtGui.framework/Versions/5/Headers/qimagereader.h \
		../../../Applications/5.2.0/clang_64/lib/QtGui.framework/Versions/5/Headers/QMovie \
		../../../Applications/5.2.0/clang_64/lib/QtGui.framework/Versions/5/Headers/qmovie.h \
		../../../Applications/5.2.0/clang_64/lib/QtCore.framework/Versions/5/Headers/QWaitCondition \
		../../../Applications/5.2.0/clang_64/lib/QtCore.framework/Versions/5/Headers/qwaitcondition.h \
		../../../Applications/5.2.0/clang_64/lib/QtCore.framework/Versions/5/Headers/QMutex \
		../../../Applications/5.2.0/clang_64/lib/QtCore.framework/Versions/5/Headers/qmutex.h \
		../../../Applications/5.2.0/clang_64/lib/QtCore.framework/Versions/5/Headers/QRect \
		../../../Applications/5.2.0/clang_64/lib/QtCore.framework/Versions/5/Headers/qrect.h \
		../../../Applications/5.2.0/clang_64/lib/QtCore.framework/Versions/5/Headers/QDebug \
		../../../Applications/5.2.0/clang_64/lib/QtCore.framework/Versions/5/Headers/qdebug.h \
		../../../Applications/5.2.0/clang_64/lib/QtGui.framework/Versions/5/Headers/QPainter \
		../../../Applications/5.2.0/clang_64/lib/QtGui.framework/Versions/5/Headers/qpainter.h \
		../../../Applications/5.2.0/clang_64/lib/QtNetwork.framework/Versions/5/Headers/QTcpSocket \
		../../../Applications/5.2.0/clang_64/lib/QtNetwork.framework/Versions/5/Headers/qtcpsocket.h \
		/usr/local/include/opencv2/core/core.hpp \
		/usr/local/include/opencv2/core/types_c.h \
		/usr/local/include/opencv2/core/version.hpp \
		/usr/local/include/opencv2/core/operations.hpp \
		/usr/local/include/opencv2/core/mat.hpp \
		/usr/local/include/opencv2/video/video.hpp \
		/usr/local/include/opencv2/video/tracking.hpp \
		/usr/local/include/opencv2/imgproc/imgproc.hpp \
		/usr/local/include/opencv2/imgproc/types_c.h \
		/usr/local/include/opencv2/core/core_c.h \
		/usr/local/include/opencv2/video/background_segm.hpp \
		cvmatandqimage.h \
		../../../Applications/5.2.0/clang_64/lib/QtGui.framework/Versions/5/Headers/QImage \
		../../../Applications/5.2.0/clang_64/lib/QtGui.framework/Versions/5/Headers/qimage.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o object/worker.o worker.cpp

object/moc_viewerwindow.o: moc/moc_viewerwindow.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o object/moc_viewerwindow.o moc/moc_viewerwindow.cpp

object/moc_capturebuffer.o: moc/moc_capturebuffer.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o object/moc_capturebuffer.o moc/moc_capturebuffer.cpp

object/moc_worker.o: moc/moc_worker.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o object/moc_worker.o moc/moc_worker.cpp

####### Install

install_target: first FORCE
	@test -d $(INSTALL_ROOT)/usr/local/bin || mkdir -p $(INSTALL_ROOT)/usr/local/bin
	$(DEL_FILE) -r "$(INSTALL_ROOT)/usr/local/bin/visor_cliente.app"
	
	-$(INSTALL_DIR) "visor_cliente.app" "$(INSTALL_ROOT)/usr/local/bin/visor_cliente.app"

uninstall_target: FORCE
	-$(DEL_FILE) -r "$(INSTALL_ROOT)/usr/local/bin/visor_cliente.app"
	-$(DEL_DIR) $(INSTALL_ROOT)/usr/local/bin/ 


install_vardir: first FORCE
	@test -d $(INSTALL_ROOT)/var/lib/visor_cliente || mkdir -p $(INSTALL_ROOT)/var/lib/visor_cliente
	:


install:  install_target install_vardir  FORCE

uninstall: uninstall_target   FORCE

FORCE:

